[test]
levels = ["syntax", "javascript", "install", "registration", "instantiation", "execution"]
publish = true

[test.workflows]
timeout = 600
cpu = ["!image_to_panorama"]
cuda = ["image_to_panorama"]

[test.platforms]
platforms = ["linux_cuda", "windows_cuda", "windows_portable_cuda", "windows_desktop_cuda"]