[cuda]
packages = ["flash_attn", "sageattention"]

[dependencies]
av = "*"

[pypi-dependencies]
huggingface_hub = "*"
psutil = "*"
safetensors = "*"
einops = "*"
comfy-aimdo = "*"
scipy = "*"
transformers = "*"